name: JDS Carwash Local
values:
  - key: baseUrl
    value: 'http://localhost/jds_back_2026/api'
    enabled: true
  - key: usuario
    value: ''
    enabled: true
  - key: password
    value: ''
    enabled: true
  - key: token
    value: ''
    enabled: true
  - key: documentoId
    value: ''
    enabled: true
  - key: productoId
    value: ''
    enabled: true
  - key: cantidadVenta
    value: '1'
    enabled: true
  - key: precioConIva
    value: '1000'
    enabled: true
  - key: precioAntesIva
    value: '840.34'
    enabled: true
  - key: valorIva
    value: '159.66'
    enabled: true
  - key: medioPagoId
    value: '1'
    enabled: true
  - key: valorPago
    value: '1000'
    enabled: true
  - key: invoker
    value: ventas
    enabled: true
