name: Deploy to Multiple Domains via SSH

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Construir proyecto
        run: |
          npm install
          npm run build

      - name: Configurar SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ssh.us.stackcp.com >> ~/.ssh/known_hosts

      - name: Subir a carwash.sofdla.net
        run: |
          scp -r dist/* sofdla.net@ssh.us.stackcp.com:/home/sites/36a/2/2d8ca11770/carwash.sofdla.net/

      - name: Subir a distrimedjl.sofdla.net
        run: |
          scp -r dist/* sofdla.net@ssh.us.stackcp.com:/home/sites/36a/2/2d8ca11770/distrimedjl.sofdla.net/
